apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "kro.fullname" . }}-role-binding
  labels:
    app: kro
    release: {{ .Release.Name }}
roleRef:
  kind: ClusterRole
  apiGroup: rbac.authorization.k8s.io
  name: {{ include "kro.fullname" . }}-cluster-role
subjects:
- kind: ServiceAccount
  name: {{ include "kro.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}