# permissions for end users to edit resourcegroups.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: resourcegroup-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: kro
    app.kubernetes.io/part-of: kro
    app.kubernetes.io/managed-by: kustomize
  name: resourcegroup-editor-role
rules:
- apiGroups:
  - kro.run
  resources:
  - resourcegroups
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - kro.run
  resources:
  - resourcegroups/status
  verbs:
  - get
