---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - kro.run
  resources:
  - resourcegroups
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - kro.run
  resources:
  - resourcegroups/finalizers
  verbs:
  - update
- apiGroups:
  - kro.run
  resources:
  - resourcegroups/status
  verbs:
  - get
  - patch
  - update
